### ISSUE TITLE
Content in non expanded sections 

### ISSUE THREAD

**Issue by Constey** [RedEchidnaUK/Table-of-Contents#1]
Hey, I've found that when a topic h1 is within a section which is not expanded, the toc does not show the topic. I guess it's because the h1 mark is not visible.
But could it be possible to take the section name as a topic? It's aswell in a marked div and should be detectable. What do you think?
Kind regards,
Constantin

**Comment by Constey** [comment]
In the code a section looks like this, and the Name of the section is also classified as an h2 element. so it should be possible to detect it. 
![image](https://user-images.githubusercontent.com/11457386/205674108-c30854a3-8d2e-45a7-b29a-81b6e7328807.png)
I guess the problem is that currently the queryselector is only looking for classes with the cke_editable tag, which a section does not have. I've not fully understood it, but couldn't we simple add the collapsible class to include those ?

![image](https://user-images.githubusercontent.com/11457386/205674515-9fb702d1-121d-4d38-8073-7aac8191ac2d.png)

**Comment by RedEchidnaUK** [comment]
Hi Constantin. As mentioned in the readme file, I modified this code from another author, and I expect collapsible sections didn’t exist when it was originally written (to be honest, I didn’t even know they existed until you mentioned them!) From what you have posted, it looks like it should be a simple fix. I don’t have time to look at it right now as I’m super busy, but I’ll try and look at it over the holiday period (if I remember). Thank you for bringing it to my attention.

**Comment by Constey** [comment]
Hi @RedEchidnaUK ,
i've figured it out :-) just add a:
var textBoxClassSection = '.Collapsible';
and an additional line unter the equivalent:
queryParts.push(textBoxClassSection + " " + TableofContents.h2Tag);
queryParts.push(textBoxClassSection + " " + TableofContents.h3Tag);
queryParts.push(textBoxClassSection + " " + TableofContents.h4Tag);
and now the sections will be aswell inventoried as (per default) h2Tag :-)

**Comment by RedEchidnaUK** [comment]
Hi, that’s great. That’s exactly what I thought I needed adding. I’ll make the change as soon as I have time and get it uploaded. Thanks for your help and support.

**Comment by Constey** [comment]
Sounds nice. I'll send you a pull request. Added aswell a german language file ;-)
What i aswell saw is that the ToC background is fix set to #FFFFFF so for example if you have a section wich has a blue background the ToC will have a seperated background in white, which does not look good. 

I've not yet found where it is specified, may you can have a look at this :-)
The Theme Colors could be used like this, if I am right: learn.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations

Thanks so far, and have a nice weekend
