### ISSUE TITLE
Is there a way to make it default to Text?

### ISSUE THREAD

**Issue by RedEchidnaUK** [RedEchidnaUK/Table-of-Contents#10]
This is great stuff. Is there a way to make it default to Text? At the moment it defaults to neither text nor markdown, which means all of the existing pages show nothing until I edit each page to select text.

_Originally posted by @robstewart-nz in https://github.com/RedEchidnaUK/Table-of-Contents/issues/8#issuecomment-1897716686_

**Comment by RedEchidnaUK** [comment]
@robstewart-nz New version released with a fix to ensure it defaults to Text for instances where the webpart was on an existing page. New webparts always defaulted correctly.

**Comment by robstewart-nz** [comment]
Amazing, thank you, any way to buy you a coffee for these updates?

**Comment by RedEchidnaUK** [comment]
Thank you, that’s a very kind offer, but I’m just glad someone finds it useful. If you still really want to do something, just put some money in the next charity donation box you see on my my behalf.
