### ISSUE TITLE
Sticky mode not working anymore

### ISSUE THREAD

**Issue by TomJacobsSpikes** [RedEchidnaUK/Table-of-Contents#12]
Since recently i noticed that on pages configured with table of contents the "sticky mode" where i expect that the TOC stays visible while scrolling down, this is not happening anymore. 

i upgrade to version 1.7.0.0 but that does not solve the problem. 

any news on that issue ? 
thanks a lot,
Tom.

**Comment by RedEchidnaUK** [comment]
Hi Tom,

As mentioned in the documentation, 'Sticky mode' works by manipulating Microsoft's CSS as the code that makes it 'Sticky' needs to be outside of my web part. Unfortunately, this means it can break without notice and I rely on community feedback to inform me of this. Thank you for letting me know.

Anyway, I've pushed a new version which should fix the issue.

**Comment by stormanh** [comment]
Thx @RedEchidnaUK !  I've confirmed that v1.7.1.0 has resolved the issue that was raised by Tom.  What was the required fix?

**Comment by RedEchidnaUK** [comment]
Thanks for confirming.
A new DIV has been added to the HTML. So the sticky position now has to be added to the great grandfather element.

**Comment by TomJacobsSpikes** [comment]
> Hi Tom,
> 
> As mentioned in the documentation, 'Sticky mode' works by manipulating Microsoft's CSS as the code that makes it 'Sticky' needs to be outside of my web part. Unfortunately, this means it can break without notice and I rely on community feedback to inform me of this. Thank you for letting me know.
> 
> Anyway, I've pushed a new version which should fix the issue.

Yes, it works !
Thanks for the quick fix
regards,
Tom.
