### ISSUE TITLE
Single apostrophe is not rendered correctly when used in Heading

### ISSUE THREAD

**Issue by stormanh** [RedEchidnaUK/Table-of-Contents#14]
When a single apostrophe: ' is used it's being rendered as &#39; in the webpart as shown below.

![image](https://github.com/user-attachments/assets/50e0bd0d-0d16-4359-b9bd-89b60dcc4e44)

**Comment by RedEchidnaUK** [comment]
@stormanh Another release for you :) 

This should fix the apostrophe bug. I just hope I haven't introduced another bug in the process.

**Comment by stormanh** [comment]
@RedEchidnaUK Confirmed working for the single apostrophe issue. Thanks for the speedy turn around!
