### ISSUE TITLE
Titles and Edit Webpart changed to German

### ISSUE THREAD

**Issue by asads2022** [RedEchidnaUK/Table-of-Contents#3]
![image](https://user-images.githubusercontent.com/130547675/231399079-720ec873-6844-4c64-a59e-71dda24c5a06.png)

The titles and Edit Webpart have changed into German.  Was fine just after I installed it.  Default language for the website is English.  My personal settings also changed to English.

Any help?

**Comment by RedEchidnaUK** [comment]
I've published a new version (1.3.2) which hopefully doesn't have this bug. I haven't been able to confirm 100% as I wasn't able to reproduce it, but I'm reasonable confident I've fixed it.

**Comment by asads2022** [comment]
Thank you! That new version has resolved the issue after I updated the app and refreshed the web page.
