### ISSUE TITLE
Default text colour "hidden" when using standard dark colour for vertical section

### ISSUE THREAD

**Issue by rgould77** [RedEchidnaUK/Table-of-Contents#4]
Usually, text will invert when using the darkest (strong) section background colour.  This webpart does not, which keeps the text colour the same as the background colour making it invisible.  Can this invert (change to white) automatically, or is the webpart colours customisable?
![example](https://user-images.githubusercontent.com/130653650/231721464-9f3852c1-96cb-468f-871e-7d72acaa32f3.png)

**Comment by rgould77** [comment]
Sorry, way out of my depth - but found this:  https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds

**Comment by RedEchidnaUK** [comment]
I will try and take a look, but I can't promise anything as I'm not a SharePoint dev or even a web developer, so slightly out of my depth as well on this one.

**Comment by rgould77** [comment]
Thanks!  I've noticed that the header text DOES work correctly, and I have been able to find at least some of the elements required to make it work....

**Comment by RedEchidnaUK** [comment]
I've just pushed an updated version which should fix the themes issue. Please try it and let me know.

**Comment by rgould77** [comment]
Thats it!  Working well now, thank-you very much for correcting that.
