### ISSUE TITLE
No more H1 in text webpart

### ISSUE THREAD

**Issue by blimts** [RedEchidnaUK/Table-of-Contents#7]
Seems MS, in trying to conform to accessibility standard, will only allow one H1 per page, which means it's now reserved for page title. So text web part will now only have H2, H3, H4. They rolled out this change without documentation and warning. So the TOC web part is broken for now because they've rolled this out on my tenant.

**Comment by RedEchidnaUK** [comment]
I’ve not seen that on any of the tenants I have access to at the moment, but it doesn’t surprise me if Microsoft make changes without warning. Interestingly though, the ToC webpart doesn’t use H1 tags, as the text webpart has only ever used H2, H3 and H4. It is possible they have changed something else which has broken the ToC

**Comment by blimts** [comment]
Ah, I've figured it out. Because existing pages that have the ToC web part was created on the old styles with H1, they continue to render fine. Now that they rolled out that "new" compliant style to my tenant, when I edit an existing page, I have to go through all the headers on the page to reassign the new style and ToC will rebuild.
