### ISSUE TITLE
Support for headings in Markdown web part?

### ISSUE THREAD

**Issue by markcjp** [RedEchidnaUK/Table-of-Contents#8]
Hi, would it be difficult to pick up headings inside Markdown web parts?

**Comment by RedEchidnaUK** [comment]
Hi,
I’ve had a quick look and it may be possible, but would require a reasonable amount of effort as the Markdown web part doesn’t indicate itself via a class which is how the text web part is found. So you would have to find the part via another means, and then search the html for the relevant headings.

**Comment by RedEchidnaUK** [comment]
Hi @markcjp I've finally found time to release a new version (v1.6.0) with support for the Markdown web parts.

**Comment by markcjp** [comment]
Thank you so much - it works with Markdown headings like a charm!

**Comment by robstewart-nz** [comment]
This is great stuff. Is there a way to make it default to Text? At the moment it defaults to neither text nor markdown, which means all of the existing pages show nothing until I edit each page to select text.
