### ISSUE TITLE
ToC over multiple sections

### ISSUE THREAD

**Issue by mtengmo** [RedEchidnaUK/Table-of-Contents#9]
Is it possible to have it sticky over multple sections?

**Comment by RedEchidnaUK** [comment]
Hi,

I’m not really sure what you mean. Could you please elaborate or provide some screenshots etc. of what you mean.

Thanks

**Comment by mtengmo** [comment]
I have three sections on this page, created from the left side of the page. 
![image](https://github.com/RedEchidnaUK/Table-of-Contents/assets/17195619/66f59bcd-e0fe-4dcb-97c0-1b15d25dc046)

The ToC will only stick to the first section. 

![image](https://github.com/RedEchidnaUK/Table-of-Contents/assets/17195619/190a47d9-1bbf-4b65-ba35-68f73c72e2b8)
Ok, section 1.

![image](https://github.com/RedEchidnaUK/Table-of-Contents/assets/17195619/ec50f6b9-911d-439e-8ebb-9eee5ba3d015)
Section 2, the sticky part is gone, it doesn´t go down this section. 

![image](https://github.com/RedEchidnaUK/Table-of-Contents/assets/17195619/30c290bf-520a-4f4c-bfea-406352690a08)
Overall picture of page.

Does it makes sense? I really like the options with different background color for different part of the page, because it makes it´s  easier to read the page if it´s long.

**Comment by mtengmo** [comment]
I was able to solve it with the vertical selection. 
![image](https://github.com/RedEchidnaUK/Table-of-Contents/assets/17195619/195d6f1d-5cf6-4a74-a0bb-5cff1a0dafb9)

**Comment by RedEchidnaUK** [comment]
Sorry,  meant to update this over the weekend. I did take a look and it doesn’t seem that it would be possible due to the way the DOM has been created and the way the Sticky CSS position works. 

I was going to suggest using the vertical section as that’s what I do, but it looks like you already found that workaround.

**Comment by mtengmo** [comment]
Yes, didn´t know about vertical selection. Maybe something to mention in the docs :)

**Comment by RedEchidnaUK** [comment]
Good idea. I’ve added some more information.
